### ISSUE TITLE
hide and show

### ISSUE THREAD

**Issue by kingscode99** [kingscode99/MiniProjectTeam7#1]

**Comment by kjk0122** [comment]
일단 먼저 적어보자

**Comment by lcoeda** [comment]
저는 아까 저희가 설정한 app.route 경로 한 번 만들어보겠습니다.

**Comment by kjk0122** [comment]
이미지 업로드 관련 fakepath로 인해 경로설정에서 애먹고 있음

대체재로 url 업로드도 추가하는 것으로 추가해놓음
fakepath 뚫는 법 계속 찾는중
